name: Test and Dry Run

on:
    pull_request:
        types: [opened, synchronize, reopened, ready_for_review]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-node@v3
              with:
                  node-version: ${{ secrets.NODE_VERSION }}

            - uses: actions/checkout@v3

            - name: Cache node modules
              uses: actions/cache@v3
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-build-cache-node-modules-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-build-cache-node-modules-
                      ${{ runner.os }}-build-
                      ${{ runner.os }}-

            - name: Install Dependencies
              run: npm ci

            - name: Run Tests
              run: npm run test

    publishDryRun:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        permissions:
            id-token: write
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ secrets.NODE_VERSION }}
                  registry-url: "https://registry.npmjs.org"

            - name: Use dependencies cache
              uses: actions/cache@v3
              with:
                  path: ~/.npm
                  key: npm-${{ hashFiles('package-lock.json') }}
                  restore-keys: npm-

            - name: Install dependencies
              run: npm ci --ignore-scripts --no-audit --no-fund

            - name: Verify package can be published
              run: npm publish --dry-run --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
